version: "3"
services:
  my-node-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=3000
