services:
  reservations:
    depends_on:
      - sleepr-mongo
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9231:9231'
    volumes:
      - .:/usr/src/app

  auth:
    depends_on:
      - sleepr-mongo
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:debug auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
      - '9232:9232'
    volumes:
      - .:/usr/src/app
  sleepr-mongo:
    image: mongo
