// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.1
//   protoc               v3.20.3
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'auth';

export interface GetAuthTokenPayload {
  userId: string;
  email: string;
}

export interface AuthToken {
  accessToken: string;
  refreshToken: string;
}

export interface VerifyTokenPayload {
  accessToken: string;
}

export interface VerifyTokenResponse {
  isValid: boolean;
  getAuthTokenPayload: GetAuthTokenPayload | undefined;
}

export const AUTH_PACKAGE_NAME = 'auth';

export interface AuthServiceClient {
  getAuthToken(request: GetAuthTokenPayload): Observable<AuthToken>;

  verifyToken(request: VerifyTokenPayload): Observable<VerifyTokenResponse>;
}

export interface AuthServiceController {
  getAuthToken(
    request: GetAuthTokenPayload,
  ): Promise<AuthToken> | Observable<AuthToken> | AuthToken;

  verifyToken(
    request: VerifyTokenPayload,
  ):
    | Promise<VerifyTokenResponse>
    | Observable<VerifyTokenResponse>
    | VerifyTokenResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['getAuthToken', 'verifyToken'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('AuthService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('AuthService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const AUTH_SERVICE_NAME = 'AuthService';
