version: "3"

services:
  broker-services:
    build:
      context: ./../broker-micro
      dockerfile: ./../broker-micro/broker-service.dockerfile
    ports:
      - "8002:80"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
