version: "3"

services:
  postgres-container:
    image: "postgres:14.2"
    container_name: "postgres-container"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: simple-bank
    volumes:
      - /home/mint/development/software-repo/docker-data/pg/tech-school-simple-banking-app2:/var/lib/postgresql/data/

  pgadmin-container:
    image: dpage/pgadmin4:latest
    container_name: "pgadmin-container"
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - "postgres-container"
