version: "3"

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker.service.dockerfile
    restart: always
    ports:
      - "8001:8001"
    # volumes:
    #   - ./../broker-service:/app
    deploy:
      mode: replicated
      replicas: 1
    # command: ["/app/brokerApp"]

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: no
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
